#ifndef KEYCONSTANTS_H_INCLUDED
#define KEYCONSTANTS_H_INCLUDED

#include <map>
#include <string>

//This file will populate the keyboard strokes into a Map, and create a KEYPAIR class

class KeyPair
{
    //This KEYPAIR class takes in the system's official name for a keystroke
    //and OUR OWN human-friendly name for a keystroke
    public:
        KeyPair(const std::wstring &vk = L"", const std::wstring &name =L"") : VKName(vk), Name(name){}
        std::wstring VKName;
        std::wstring Name;

};

class Keys
{
    public:
        static std::map<int, KeyPair> KEYS;
};

//a map is a container that uses a key value, and a mapped value
//in this case the key value is the hexadecimal value of the actual keystroke
//the mapped value is our KEYPAIR: the first one being the system's name
//for the keystroke, and the 2nd one being OUR OWN name
std::map<int, KeyPair> Keys::KEYS = {
    {0xC1, {L"[VK_ABNT_C1]", L"[Abnt C1]"}},
    {0xC2, {L"[VK_ABNT_C2]", L"[Abnt C2]"}},
    {0x6B, {L"[VK_ADD]", L"[Numpad +]"}},
    {0xF6, {L"[VK_ATTN]", L"[Attn]"}},
    {0x08, {L"[VK_BACK]", L"[Backspace]"}},
    {0x03, {L"[VK_CANCEL]", L"[Break]"}},
    {0x0C, {L"[VK_CLEAR]", L"[Clear]"}},
    {0xF7, {L"[VK_CRSEL]", L"[Cr Sel]"}},
    {0x6E, {L"[VK_DECIMAL]", L"[Numpad .]"}},
    {0x6F, {L"[VK_DIVIDE]", L"[Numpad /]"}},
    {0xF9, {L"[VK_EREOF]", L"[Er Eof]"}},
    {0x1B, {L"[VK_ESCAPE]", L"[Esc]"}},
    {0x2B, {L"[VK_EXECUTE]", L"[Execute]"}},
    {0xF8, {L"[VK_EXSEL]", L"[Ex Sel]"}},
    {0xE6, {L"[VK_ICO_CLEAR]", L"[IcoClr]"}},
    {0xE3, {L"[VK_ICO_HELP]", L"[IcoHlp]"}},
    {0x30, {L"[VK_KEY_0]", L"[D0]"}},
    {0x31, {L"[VK_KEY_1]", L"[D1]"}},
    {0x32, {L"[VK_KEY_2]", L"[D2]"}},
    {0x33, {L"[VK_KEY_3]", L"[D3]"}},
    {0x34, {L"[VK_KEY_4]", L"[D4]"}},
    {0x35, {L"[VK_KEY_5]", L"[D5]"}},
    {0x36, {L"[VK_KEY_6]", L"[D6]"}},
    {0x37, {L"[VK_KEY_7]", L"[D7]"}},
    {0x38, {L"[VK_KEY_8]", L"[D8]"}},
    {0x39, {L"[VK_KEY_9]", L"[D9]"}},
    {0x41, {L"[VK_KEY_A]", L"[A]"}},
    {0x42, {L"[VK_KEY_B]", L"[B]"}},
    {0x43, {L"[VK_KEY_C]", L"[C]"}},
    {0x44, {L"[VK_KEY_D]", L"[D]"}},
    {0x45, {L"[VK_KEY_E]", L"[E]"}},
    {0x46, {L"[VK_KEY_F]", L"[F]"}},
    {0x47, {L"[VK_KEY_G]", L"[G]"}},
    {0x48, {L"[VK_KEY_H]", L"[H]"}},
    {0x49, {L"[VK_KEY_I]", L"[I]"}},
    {0x4A, {L"[VK_KEY_J]", L"[J]"}},
    {0x4B, {L"[VK_KEY_K]", L"[K]"}},
    {0x4C, {L"[VK_KEY_L]", L"[L]"}},
    {0x4D, {L"[VK_KEY_M]", L"[M]"}},
    {0x4E, {L"[VK_KEY_N]", L"[N]"}},
    {0x4F, {L"[VK_KEY_O]", L"[O]"}},
    {0x50, {L"[VK_KEY_P]", L"[P]"}},
    {0x51, {L"[VK_KEY_Q]", L"[Q]"}},
    {0x52, {L"[VK_KEY_R]", L"[R]"}},
    {0x53, {L"[VK_KEY_S]", L"[S]"}},
    {0x54, {L"[VK_KEY_T]", L"[T]"}},
    {0x55, {L"[VK_KEY_U]", L"[U]"}},
    {0x56, {L"[VK_KEY_V]", L"[V]"}},
    {0x57, {L"[VK_KEY_W]", L"[W]"}},
    {0x58, {L"[VK_KEY_X]", L"[X]"}},
    {0x59, {L"[VK_KEY_Y]", L"[Y]"}},
    {0x5A, {L"[VK_KEY_Z]", L"[Z]"}},
    {0x6A, {L"[VK_MULTIPLY]", L"[Numpad *]"}},
    {0xFC, {L"[VK_NONAME]", L"[NoName]"}},
    {0x60, {L"[VK_NUMPAD0]", L"[N0]"}},
    {0x61, {L"[VK_NUMPAD1]", L"[N1]"}},
    {0x62, {L"[VK_NUMPAD2]", L"[N2]"}},
    {0x63, {L"[VK_NUMPAD3]", L"[N3]"}},
    {0x64, {L"[VK_NUMPAD4]", L"[N4]"}},
    {0x65, {L"[VK_NUMPAD5]", L"[N5]"}},
    {0x66, {L"[VK_NUMPAD6]", L"[N6]"}},
    {0x67, {L"[VK_NUMPAD7]", L"[N7]"}},
    {0x68, {L"[VK_NUMPAD8]", L"[N8]"}},
    {0x69, {L"[VK_NUMPAD9]", L"[N9]"}},
    {0xBA, {L"[VK_OEM_1]", L"[OEM_1 (: ;)]"}},
    {0xE2, {L"[VK_OEM_102]", L"[OEM_102 (> <)]"}},
    {0xBF, {L"[VK_OEM_2]", L"[OEM_2 (? /)]"}},
    {0xC0, {L"[VK_OEM_3]", L"[OEM_3 (~ `)]"}},
    {0xDB, {L"[VK_OEM_4]", L"[OEM_4 ({ [)]"}},
    {0xDC, {L"[VK_OEM_5]", L"[OEM_5 (| \\)]"}},
    {0xDD, {L"[VK_OEM_6]", L"[OEM_6 (} ])]"}},
    {0xDE, {L"[VK_OEM_7]", L"[OEM_7 (\" ')]"}},
    {0xDF, {L"[VK_OEM_8]", L"[OEM_8 (§ !)]"}},
    {0xF0, {L"[VK_OEM_ATTN]", L"[Oem Attn]"}},
    {0xF3, {L"[VK_OEM_AUTO]", L"[Auto]"}},
    {0xE1, {L"[VK_OEM_AX]", L"[Ax]"}},
    {0xF5, {L"[VK_OEM_BACKTAB]", L"[Back Tab]"}},
    {0xFE, {L"[VK_OEM_CLEAR]", L"[OemClr]"}},
    {0xBC, {L"[VK_OEM_COMMA]", L"[OEM_COMMA (< ,)]"}},
    {0xF2, {L"[VK_OEM_COPY]", L"[Copy]"}},
    {0xEF, {L"[VK_OEM_CUSEL]", L"[Cu Sel]"}},
    {0xF4, {L"[VK_OEM_ENLW]", L"[Enlw]"}},
    {0xF1, {L"[VK_OEM_FINISH]", L"[Finish]"}},
    {0x95, {L"[VK_OEM_FJ_LOYA]", L"[Loya]"}},
    {0x93, {L"[VK_OEM_FJ_MASSHOU]", L"[Mashu]"}},
    {0x96, {L"[VK_OEM_FJ_ROYA]", L"[Roya]"}},
    {0x94, {L"[VK_OEM_FJ_TOUROKU]", L"[Touroku]"}},
    {0xEA, {L"[VK_OEM_JUMP]", L"[Jump]"}},
    {0xBD, {L"[VK_OEM_MINUS]", L"[OEM_MINUS (_ -)]"}},
    {0xEB, {L"[VK_OEM_PA1]", L"[OemPa1]"}},
    {0xEC, {L"[VK_OEM_PA2]", L"[OemPa2]"}},
    {0xED, {L"[VK_OEM_PA3]", L"[OemPa3]"}},
    {0xBE, {L"[VK_OEM_PERIOD]", L"[OEM_PERIOD (> .)]"}},
    {0xBB, {L"[VK_OEM_PLUS]", L"[OEM_PLUS (+ =)]"}},
    {0xE9, {L"[VK_OEM_RESET]", L"[Reset]"}},
    {0xEE, {L"[VK_OEM_WSCTRL]", L"[WsCtrl]"}},
    {0xFD, {L"[VK_PA1]", L"[Pa1]"}},
    {0xE7, {L"[VK_PACKET]", L"[Packet]"}},
    {0xFA, {L"[VK_PLAY]", L"[Play]"}},
    {0xE5, {L"[VK_PROCESSKEY]", L"[Process]"}},
    {0x0D, {L"[VK_RETURN]", L"[Enter]"}},
    {0x29, {L"[VK_SELECT]", L"[Select]"}},
    {0x6C, {L"[VK_SEPARATOR]", L"[Separator]"}},
    {0x20, {L"[VK_SPACE]", L"[Space]"}},
    {0x6D, {L"[VK_SUBTRACT]", L"[Num -]"}},
    {0x09, {L"[VK_TAB]", L"[Tab]"}},
    {0xFB, {L"[VK_ZOOM]", L"[Zoom]"}},
    {0x1E, {L"[VK_ACCEPT]", L"[Accept]"}},
    {0x5D, {L"[VK_APPS]", L"[Context Menu]"}},
    {0xA6, {L"[VK_BROWSER_BACK]", L"[Browser Back]"}},
    {0xAB, {L"[VK_BROWSER_FAVORITES]", L"[Browser Favorites]"}},
    {0xA7, {L"[VK_BROWSER_FORWARD]", L"[Browser Forward]"}},
    {0xAC, {L"[VK_BROWSER_HOME]", L"[Browser Home]"}},
    {0xA8, {L"[VK_BROWSER_REFRESH]", L"[Browser Refresh]"}},
    {0xAA, {L"[VK_BROWSER_SEARCH]", L"[Browser Search]"}},
    {0xA9, {L"[VK_BROWSER_STOP]", L"[Browser Stop]"}},
    {0x14, {L"[VK_CAPITAL]", L"[Caps Lock]"}},
    {0x1C, {L"[VK_CONVERT]", L"[Convert]"}},
    {0x2E, {L"[VK_DELETE]", L"[Delete]"}},
    {0x28, {L"[VK_DOWN]", L"[Arrow Down]"}},
    {0x23, {L"[VK_END]", L"[End]"}},
    {0x70, {L"[VK_F1]", L"[F1]"}},
    {0x79, {L"[VK_F10]", L"[F10]"}},
    {0x7A, {L"[VK_F11]", L"[F11]"}},
    {0x7B, {L"[VK_F12]", L"[F12]"}},
    {0x7C, {L"[VK_F13]", L"[F13]"}},
    {0x7D, {L"[VK_F14]", L"[F14]"}},
    {0x7E, {L"[VK_F15]", L"[F15]"}},
    {0x7F, {L"[VK_F16]", L"[F16]"}},
    {0x80, {L"[VK_F17]", L"[F17]"}},
    {0x81, {L"[VK_F18]", L"[F18]"}},
    {0x82, {L"[VK_F19]", L"[F19]"}},
    {0x71, {L"[VK_F2]", L"[F2]"}},
    {0x83, {L"[VK_F20]", L"[F20]"}},
    {0x84, {L"[VK_F21]", L"[F21]"}},
    {0x85, {L"[VK_F22]", L"[F22]"}},
    {0x86, {L"[VK_F23]", L"[F23]"}},
    {0x87, {L"[VK_F24]", L"[F24]"}},
    {0x72, {L"[VK_F3]", L"[F3]"}},
    {0x73, {L"[VK_F4]", L"[F4]"}},
    {0x74, {L"[VK_F5]", L"[F5]"}},
    {0x75, {L"[VK_F6]", L"[F6]"}},
    {0x76, {L"[VK_F7]", L"[F7]"}},
    {0x77, {L"[VK_F8]", L"[F8]"}},
    {0x78, {L"[VK_F9]", L"[F9]"}},
    {0x18, {L"[VK_FINAL]", L"[Final]"}},
    {0x2F, {L"[VK_HELP]", L"[Help]"}},
    {0x24, {L"[VK_HOME]", L"[Home]"}},
    {0xE4, {L"[VK_ICO_00]", L"[Ico00 *]"}},
    {0x2D, {L"[VK_INSERT]", L"[Insert]"}},
    {0x17, {L"[VK_JUNJA]", L"[Junja]"}},
    {0x15, {L"[VK_KANA]", L"[Kana]"}},
    {0x19, {L"[VK_KANJI]", L"[Kanji]"}},
    {0xB6, {L"[VK_LAUNCH_APP1]", L"[App1]"}},
    {0xB7, {L"[VK_LAUNCH_APP2]", L"[App2]"}},
    {0xB4, {L"[VK_LAUNCH_MAIL]", L"[Mail]"}},
    {0xB5, {L"[VK_LAUNCH_MEDIA_SELECT]", L"[Media]"}},
    {0x01, {L"[VK_LBUTTON]", L"[Left Button **]"}},
    {0xA2, {L"[VK_LCONTROL]", L"[Left Ctrl]"}},
    {0x25, {L"[VK_LEFT]", L"[Arrow Left]"}},
    {0xA4, {L"[VK_LMENU]", L"[Left Alt]"}},
    {0xA0, {L"[VK_LSHIFT]", L"[Left Shift]"}},
    {0x5B, {L"[VK_LWIN]", L"[Left Win]"}},
    {0x04, {L"[VK_MBUTTON]", L"[Middle Button **]"}},
    {0xB0, {L"[VK_MEDIA_NEXT_TRACK]", L"[Next Track]"}},
    {0xB3, {L"[VK_MEDIA_PLAY_PAUSE]", L"[Play / Pause]"}},
    {0xB1, {L"[VK_MEDIA_PREV_TRACK]", L"[Previous Track]"}},
    {0xB2, {L"[VK_MEDIA_STOP]", L"[Stop]"}},
    {0x1F, {L"[VK_MODECHANGE]", L"[Mode Change]"}},
    {0x22, {L"[VK_NEXT]", L"[Page Down]"}},
    {0x1D, {L"[VK_NONCONVERT]", L"[Non Convert]"}},
    {0x90, {L"[VK_NUMLOCK]", L"[Num Lock]"}},
    {0x92, {L"[VK_OEM_FJ_JISHO]", L"[Jisho]"}},
    {0x13, {L"[VK_PAUSE]", L"[Pause]"}},
    {0x2A, {L"[VK_PRINT]", L"[Print]"}},
    {0x21, {L"[VK_PRIOR]", L"[Page Up]"}},
    {0x02, {L"[VK_RBUTTON]", L"[Right Button **]"}},
    {0xA3, {L"[VK_RCONTROL]", L"[Right Ctrl]"}},
    {0x27, {L"[VK_RIGHT]", L"[Arrow Right]"}},
    {0xA5, {L"[VK_RMENU]", L"[Right Alt]"}},
    {0xA1, {L"[VK_RSHIFT]", L"[Right Shift]"}},
    {0x5C, {L"[VK_RWIN]", L"[Right Win]"}},
    {0x91, {L"[VK_SCROLL]", L"[Scrol Lock]"}},
    {0x5F, {L"[VK_SLEEP]", L"[Sleep]"}},
    {0x2C, {L"[VK_SNAPSHOT]", L"[Print Screen]"}},
    {0x26, {L"[VK_UP]", L"[Arrow Up]"}},
    {0xAE, {L"[VK_VOLUME_DOWN]", L"[Volume Down]"}},
    {0xAD, {L"[VK_VOLUME_MUTE]", L"[Volume Mute]"}},
    {0xAF, {L"[VK_VOLUME_UP]", L"[Volume Up]"}},
    {0x05, {L"[VK_XBUTTON1]", L"[X Button 1 **]"}},
    {0x06, {L"[VK_XBUTTON2]", L"[X Button 2 **]"}},
};

#endif // KEYCONSTANTS_H_INCLUDED
